### PR TITLE
Update MemcachedConnector.php

### PR DESCRIPTION
**Pull request by agentelinux**
compatibility with Laravel 5.3

### CODE REVIEW

**Comment by agentelinux** [comment]
tested

**Comment by agentelinux** [comment]
ops.
You can accept please.

**Comment by cedricziel** [comment]
Thank you! I will merge and release a new major version today.

**Comment by cedricziel** [comment]
Squashed and merged manually. Thank you for your contribution! 

I tagged v2.0.0 and simplified the adapter to be more similar so the base adapter in regards to the available options. Can you please test v2.0.0?

**Comment by agentelinux** [comment]
Perfect

Yes I can.

Branch: master, ok?

Em 12 de jan de 2017 08:23, "Cedric Ziel" <notifications@github.com>
escreveu:

**Comment by cedricziel** [comment]
The tag is already on packagist, so theoretically you can use `2.0.*` as version constraint in your composer.json file.

**Comment by agentelinux** [comment]
Hi Cedric,
My deploy in GAE fail.
Look: https://api-sk.appspot.com/

RuntimeException in MemcachedConnector.php line 21: Could not establish Memcached connection.

    in MemcachedConnector.php line 21
    at MemcachedConnector->validateConnection(object(Memcached)) in MemcachedConnector.php line 40
    at MemcachedConnector->connect(array(array('host' => '127.0.0.1', 'port' => '11211', 'weight' => '100')), null, array(), array(null, null)) in MemcachedNoversionServiceProvider.php line 31

make sense?

**Comment by cedricziel** [comment]
Yep. I think you already figured it out, but you need to set it from the environment variables `MEMCACHE_PORT_11211_TCP_ADDR` and `MEMCACHE_PORT_11211_TCP_PORT` on appengine flex.

**Comment by cedricziel** [comment]
Reference: https://cloud.google.com/appengine/docs/flexible-old/java/caching-application-data

I think I'll put it in the README, I thought it was obvious, because it's in the docs, but apparently it's not ;)

**Comment by cedricziel** [comment]
https://github.com/cedricziel/l5-memcached-noversion/blob/master/README.md#appengine-flexible-environment

**Comment by agentelinux** [comment]
I try and not success. Could not establish Memcached connection.
I return by version without connect.
 
without --> https://api-sk.appspot-preview.com/

**Comment by agentelinux** [comment]
If you test the page login, him will return erro of the crsf. It will be other problem from memcached?

**Pull request closed without merging**
